app:
  jwtExpirationMs: 60000000
  jwtSecret: ${JWT_SECRET_KEY}
server:
  port: 8083
spring:
  application:
    name: ledger
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/ledger
    username: beval
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
snowflake:
  workerId: 4
springdoc:
  api-docs:
    path: /api/v1/ledger/api-docs
  swagger-ui:
    path: /api/v1/ledger/swagger-ui


