CREATE TABLE USER_ASSETS
(
    ETH DECIMAL(21, 12) NOT NULL DEFAULT 0,
    USDT DECIMAL(21, 12) NOT NULL DEFAULT 0,
    WETH DECIMAL(21, 12) NOT NULL DEFAULT 0,
    UNI DECIMAL(21, 12) NOT NULL DEFAULT 0
);