server:
  port: 8086
spring:
  application:
    name: userwallet
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/userwallet
    username: beval
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
snowflake:
  workerId: 3
springdoc:
  api-docs:
    path: /api/v1/userwallet/api-docs
  swagger-ui:
    path: /api/v1/userwallet/swagger-ui


