server:
    port: 8080

spring:
    application:
        name: api-gateway
    zipkin:
        base-url: http://localhost:9411
    cloud:
       gateway:
          routes:
            - id: customer
              uri: lb://CUSTOMER
              predicates:
                - Path=/api/v1/customers/**
              filters:
                - name: JwtAuthenticationFilter
            - id: auth
              uri: lb://AUTH
              predicates:
                - Path=/api/v1/auth/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true