server:
    port: 8080

spring:
    application:
        name: api-gateway
    zipkin:
        base-url: http://localhost:9411
    cloud:
       gateway:
          routes:
            - id: auth
              uri: lb://AUTH
              predicates:
                - Path=/api/v1/auth/**
            - id: marketengine
              uri: lb://MARKETENGINE
              predicates:
                - Path=/api/v1/market/**
              filters:
                - name: JwtAuthenticationFilter
            - id: userwallet
              uri: lb://USERWALLET
              predicates:
                - Path=/api/v1/userwallet/**
              filters:
                - name: JwtAuthenticationFilter
            - id: payment
              uri: lb://PAYMENT
              predicates:
                - Path=/api/v1/payment/**
              filters:
                - name: JwtAuthenticationFilter
            - id: ledger
              uri: lb://LEDGER
              predicates:
                - Path=/api/v1/ledger/**
              filters:
                - name: JwtAuthenticationFilter

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true