app:
  binance:
    baseUrl: "https://testnet.binance.vision"
    apiKey: ${BINANCE_API_KEY}
    secretKey: ${BINANCE_SECRET_KEY}
server:
  port: 8085
spring:
  application:
    name: marketengine
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
snowflake:
  workerId: 2
springdoc:
  api-docs:
    path: /api/v1/market/api-docs
  swagger-ui:
    path: /api/v1/market/swagger-ui



