app:
  binance:
    baseUrl: "https://testnet.binance.vision"
    apiKey: ${BINANCE_API_KEY}
    secretKey: ${BINANCE_SECRET_KEY}
server:
  port: 8085
spring:
  application:
    name: marketengine
#  datasource:
#    password: password
#    url: jdbc:postgresql://postgres:5432/marketengine
#    username: amigoscode
  zipkin:
    base-url: http://zipkin:9411
#  flyway:
#      url: jdbc:postgresql://postgres:5432
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
snowflake:
  workerId: 2


