app:
  web3:
    network: "goerli"
    infura-api-key: ${INFURA_API_KEY}
    wallet-private-key: ${WALLET_PRIVATE_KEY}
    wallet-address: "0x98c415A7dDF5D0ca01b391e1d2079ECeFC997539"
server:
  port: 8087
spring:
  application:
    name: privatewallet
  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
    url: redis://localhost:6379
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
springdoc:
  api-docs:
    path: /api/v1/privatewallet/api-docs
  swagger-ui:
    path: /api/v1/privatewallet/swagger-ui
#logging:
#  level:
#    root: debug
