app:
  web3:
    network: "goerli"
    infura-api-key: ${INFURA_API_KEY}
    wallet-address: "0x98c415A7dDF5D0ca01b391e1d2079ECeFC997539"
server:
  port: 8087
spring:
  application:
    name: privatewallet
#  datasource:
#    password: password
#    url: jdbc:postgresql://localhost:5432/privatewallet
#    username: amigoscode
#    driver-class-name: org.postgresql.Driver
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

