app:
  jwtExpirationMs: 60000000
  jwtSecret: ${JWT_SECRET_KEY}
server:
  port: 8084
spring:
  application:
    name: auth
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/auth
    username: beval
    driver-class-name: org.postgresql.Driver
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
snowflake:
  workerId: 1
springdoc:
  api-docs:
    path: /api/v1/auth/api-docs
  swagger-ui:
    path: /api/v1/auth/swagger-ui


