app:
  jwtExpirationMs: 60000000
  jwtSecret: ${JWT_SECRET_KEY}
server:
  port: 8084
spring:
  application:
    name: auth
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/auth
    username: amigoscode
  zipkin:
    base-url: http://zipkin:9411
#  flyway:
#      url: jdbc:postgresql://postgres:5432
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
snowflake:
  workerId: 1


