app:
  stripe:
    apiKey: ${STRIPE_API_KEY}
    secretKey: ${STRIPE_SECRET_KEY}
    webHookSecret: ${STRIPE_WEBHOOK_SECRET}
    successUrl: http://google.com
    cancelUrl: http://yahoo.com
server:
  port: 8088

spring:
  application:
    name: payment
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
springdoc:
  api-docs:
    path: /api/v1/payment/api-docs
  swagger-ui:
    path: /api/v1/payment/swagger-ui


